export const actionType = {
  // auth
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SET_AUTH_ERROR: "SET_AUTH_ERROR",
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  // movie
  FETCH_MOVIES_REQUEST: "FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIE_REQUEST: "FETCH_MOVIE_REQUEST",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  FETCH_MOVIES_WITH_PAGINATION_REQUEST: "FETCH_MOVIES_WITH_PAGINATION_REQUEST",
  FETCH_MOVIES_WITH_PAGINATION_SUCCESS: "FETCH_MOVIES_WITH_PAGINATION_SUCCESS",
  FETCH_MOVIE_SHOWTIMES_REQUEST: "FETCH_MOVIE_SHOWTIMES_REQUEST",
  FETCH_MOVIE_SHOWTIMES_SUCCESS: "FETCH_MOVIE_SHOWTIMES_SUCCESS",
  CREATE_MOVIE_REQUEST: "CREATE_MOVIE_REQUEST",
  CREATE_MOVIE_SUCCESS: "CREATE_MOVIE_SUCCESS",
  UPDATE_MOVIE_REQUEST: "UPDATE_MOVIE_REQUEST",
  UPDATE_MOVIE_SUCCESS: "UPDATE_MOVIE_SUCCESS",
  DELETE_MOVIE_REQUEST: "DELETE_MOVIE_REQUEST",
  DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",

  // booking
  // cinema
  FETCH_CINEMA_COMPLEXES_REQUEST: "FETCH_CINEMA_COMPLEXES_REQUEST",
  FETCH_CINEMA_COMPLEXES_SUCCESS: "FETCH_CINEMA_COMPLEXES_SUCCESS",
  FETCH_CINEMA_GROUP_BY_CINEMA_COMPLEX_REQUEST:
    "FETCH_CINEMA_GROUP_BY_CINEMA_COMPLEX_REQUEST",
  FETCH_CINEMA_GROUP_BY_CINEMA_COMPLEX_SUCCESS:
    "FETCH_CINEMA_GROUP_BY_CINEMA_COMPLEX_SUCCESS",
  FETCH_CINEMA_COMPLEX_SHOWTIMES_SUCCESS:
    "FETCH_CINEMA_COMPLEX_SHOWTIMES_SUCCESS",
  FETCH_MOVIE_SHOWTIME_REQUEST: "FETCH_MOVIE_SHOWTIME_REQUEST",
  FETCH_MOVIE_SHOWTIME_SUCCESS: "FETCH_MOVIE_SHOWTIME_SUCCESS",

  // user
  FETCH_USERS_WITH_PAGINATION_REQUEST: "FETCH_USERS_WITH_PAGINATION_REQUEST",
  FETCH_USERS_WITH_PAGINATION_SUCCESS: "FETCH_USERS_WITH_PAGINATION_SUCCESS",
  FETCH_USER_DETAIL_REQUEST: "FETCH_USER_DETAIL_REQUEST",
  FETCH_USER_DETAIL_SUCCESS: "FETCH_USER_DETAIL_SUCCESS",
  FETCH_USER_TYPES_REQUEST: "FETCH_USER_TYPES_REQUEST",
  FETCH_USER_TYPES_SUCCESS: "FETCH_USER_TYPES_SUCCESS",
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
};
